// SPDX-License-Identifier: Apache-2.0
package generator

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/kungfu-systems/taolu/internal/compiler"
)

// Generate compiles a single-product Site configuration and emits the complete
// installer surface that a Site publishes. Product repositories remain unaware
// of Taolu and only publish their ordinary GitHub Release assets.
func Generate(configPath, releasesPath, bundleURL, out string) (compiler.Bundle, error) {
	if err := validateBundleURL(bundleURL); err != nil {
		return compiler.Bundle{}, err
	}
	bundle, err := compiler.Compile(configPath, releasesPath)
	if err != nil {
		return compiler.Bundle{}, err
	}
	if len(bundle.Products) != 1 {
		return compiler.Bundle{}, fmt.Errorf("installer generation requires exactly one product, got %d", len(bundle.Products))
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return compiler.Bundle{}, err
	}
	if err := compiler.Write(filepath.Join(out, "bundle.json"), bundle); err != nil {
		return compiler.Bundle{}, err
	}
	values := map[string]string{
		"@PRODUCT@":     bundle.Products[0].ID,
		"@BUNDLE_URL@":  bundleURL,
		"@BUNDLE_ROOT@": bundle.BundleRoot,
	}
	if err := writeTemplate(filepath.Join(out, "install.sh"), productInstallSH, values, 0o755); err != nil {
		return compiler.Bundle{}, err
	}
	if err := writeTemplate(filepath.Join(out, "install.ps1"), productInstallPS1, values, 0o644); err != nil {
		return compiler.Bundle{}, err
	}
	return bundle, nil
}

func validateBundleURL(raw string) error {
	if strings.ContainsAny(raw, "'\r\n") {
		return fmt.Errorf("invalid --bundle-url")
	}
	u, err := url.Parse(raw)
	if err != nil || u.Fragment != "" || (u.Scheme != "https" && u.Scheme != "file") || (u.Scheme == "https" && u.Host == "") || (u.Scheme == "file" && u.Path == "") {
		return fmt.Errorf("--bundle-url must be an absolute HTTPS or file URL")
	}
	return nil
}

func writeTemplate(path, template string, values map[string]string, mode os.FileMode) error {
	for key, value := range values {
		template = strings.ReplaceAll(template, key, value)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(template), mode); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

const productInstallSH = `#!/bin/bash
# Generated by Taolu. Source configuration is bound by @BUNDLE_ROOT@.
set -eu
product=` + "'" + `@PRODUCT@` + "'" + `
bundle_url=` + "'" + `@BUNDLE_URL@` + "'" + `
bundle_root=` + "'" + `@BUNDLE_ROOT@` + "'" + `
taolu_bin=${TAOLU_BIN:-taolu}
command -v "$taolu_bin" >/dev/null 2>&1 || { echo "install Taolu first" >&2; exit 1; }
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/taolu-product.XXXXXX")
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM
case "$bundle_url" in
  file://*) cp "${bundle_url#file://}" "$tmp_dir/bundle.json" ;;
  https://*) curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 "$bundle_url" --output "$tmp_dir/bundle.json" ;;
  *) echo "unsupported bundle URL" >&2; exit 1 ;;
esac
"$taolu_bin" install --bundle "$tmp_dir/bundle.json" --bundle-root "$bundle_root" --product "$product" --root "${TAOLU_HOME:-$HOME/.taolu}"
`

const productInstallPS1 = `# Generated by Taolu. Source configuration is bound by @BUNDLE_ROOT@.
$ErrorActionPreference = "Stop"
$product = ` + "'" + `@PRODUCT@` + "'" + `
$bundleUrl = ` + "'" + `@BUNDLE_URL@` + "'" + `
$bundleRoot = ` + "'" + `@BUNDLE_ROOT@` + "'" + `
$taolu = if ($env:TAOLU_BIN) { $env:TAOLU_BIN } else { "taolu" }
$command = Get-Command $taolu -ErrorAction SilentlyContinue
if (-not $command) { throw "Install Taolu first" }
$temp = Join-Path ([IO.Path]::GetTempPath()) ("taolu-product-" + [guid]::NewGuid())
New-Item -ItemType Directory -Path $temp | Out-Null
try {
  $bundle = Join-Path $temp "bundle.json"
  $uri = [Uri]$bundleUrl
  if ($uri.Scheme -eq "file") { Copy-Item $uri.LocalPath $bundle }
  elseif ($uri.Scheme -eq "https") { Invoke-WebRequest -UseBasicParsing -Uri $bundleUrl -OutFile $bundle }
  else { throw "Unsupported bundle URL" }
  $root = if ($env:TAOLU_HOME) { $env:TAOLU_HOME } else { Join-Path $HOME ".taolu" }
  & $taolu install --bundle $bundle --bundle-root $bundleRoot --product $product --root $root
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
} finally { Remove-Item -Recurse -Force $temp -ErrorAction SilentlyContinue }
`

// QuoteFileURL returns a deterministic file URL suitable for tests and local
// Site rehearsals. Production Sites should publish bundle.json over HTTPS.
func QuoteFileURL(path string) string {
	return "file://" + filepath.ToSlash(path)
}
